### ISSUE TITLE
1.1.1 broke all content on our site.

### ISSUE THREAD

**Issue by FrancisBou** [benjamminf/craft-neo#25] opened 2016-06-06 18:30 UTC
Since updating to 1.1.1, all Neo matrixes on our site are broken. The CMS has become obsolete and we have to revert to a previous backup. Here is a list of problem we encountered:

- Only one NEO block remains on each field, not always the first one.
- We can only add a block using the "add block above" option. (the block has a white handle).   Another "fix" for this is disabling then enabling a block and then save the entry.
- When we finish putting back the content that has been lost, we then visit the page with the neo feild it breaks the content in the same way again. Exept the content is still displayed in the front-end but not in the CMS (the order is also different then what we saved). The bug where we cannot add a block happens again. 

What happened there?

**Comment by benjamminf** [comment] 2016-06-06 20:57
Hey Francis, sorry about this. You're not the only user to report this issue. I'm honestly at a loss to explain what's going on, as I extensively tested the migration, and that the migration is quite minor. Is your site localised?

Whatever happened I'm certain your content is still there, and it's just not showing up, which you should be able to verify but checking the `neoblocks` table in the database. However Craft creates database backups automatically in the `craft/storage/backups` directory where you can restore to prior to updating.

I've removed `1.1.1` for now, and will urgently work on pushing out a fix for this.

**Comment by FrancisBou** [comment] 2016-06-06 22:05
No problem, you put some hard work in your plugins and it's much appreciated.
The website is not localized.

**Comment by fyrebase** [comment] 2016-06-07 14:32
I have a very similar problem to this. The Neo field is working on the front end but is missing from the CP

**Comment by samlous** [comment] 2016-06-08 13:48
I also noticed that this bug only happens when a neo(matrixfield) is used twice in different entries.

**Comment by fyrebase** [comment] 2016-06-08 23:26
@samlous I don't think that is the case. I only had one Neo field in use on a single page

**Comment by benjamminf** [comment] 2016-06-09 00:10
It seems like everyone is having issues but me! What I believe is the cause is the modifications I made to the element criteria model for finding blocks. `1.1.1` solved (well, attempted to solve) a bug with Neo fields that were set to be translatable. The update added a `ownerLocale` column to the `neoblockstructures` table, and it should've defaulted all the values to `null`, but it's possible that it might not be the case.

Would anyone be able to supply me a DB dump after updating Neo to `1.1.1` so I can confirm this? Thanks.

**Comment by fyrebase** [comment] 2016-06-09 00:28
@benjamminf I dm'd you in slack with a copy of my DB

**Comment by benjamminf** [comment] 2016-06-09 11:46
After scanning the DB dump (thanks for that @fyrebase) I've found the problem! I should have this fixed up tonight. Sorry for the trouble and thanks for the patience!

**Comment by samlous** [comment] 2016-06-09 11:52
Great! Really appreciate the quick response and help. Thanks!

**Closed** 2016-06-09 13:33 UTC
Labels: bug
