### ISSUE TITLE
Image file field not saved on first save

### ISSUE THREAD

**Issue by Skadi2k3** [benjamminf/craft-neo#74] opened 2017-01-16 11:40 UTC
I've got a translatable block and an image field. Upon saving (cmd + s) the block is added just fine, but the image is cleared and I have to add it again, hit save again, and then it successfully saves. Any idea as to what might cause this? I used neo 1.3.4 when creating the fields, updated to 1.4.0 but the bug persists. The block is saved on the first try when editing the main language.

**Comment by SavanaFernandes** [comment] 2017-01-20 00:26
This is happening to me as well. It happens in all languages though.

**Comment by zachshallbetter** [comment] 2017-01-20 01:10
We're experiencing this same issue. Here's a gif!

![neo-assets](https://cloud.githubusercontent.com/assets/949434/22131748/283d9f1a-de6a-11e6-86cf-d73dc051cfbe.gif)

**Comment by benjamminf** [comment] 2017-02-10 18:50
Still unable to replicate this unfortunately. I'll keep trying and update this when I figure it out...

**Comment by zachshallbetter** [comment] 2017-02-10 18:51
Thanks! If you need a db backup or anything, let me know.

**Comment by benjamminf** [comment] 2017-02-11 20:07
This is so strange, no matter what I try I can't seem to replicate this. @zachshallbetter what version of Craft and PHP are you running? I may also have to grab a DB backup. Thanks.

**Comment by benjamminf** [comment] 2017-02-11 20:10
Before you do that, I did fix #75 yesterday. Try cloning the plugin from the master branch and see if that fixes it.

**Comment by zachshallbetter** [comment] 2017-02-13 19:52
Looks like that issue is solved. I can reopen if it we discover it's still occurring.

**Comment by benjamminf** [comment] 2017-02-13 19:57
Great! I'll close it for now then.

**Comment by zachshallbetter** [comment] 2017-03-22 20:43
@benjamminf this issue seems to still be occurring (clients going a bit nuts). I've uploaded a video. any thoughts? Thanks again for your help.

![neo-image-upload](https://cloud.githubusercontent.com/assets/949434/24219803/5caaa6d2-0f05-11e7-9dda-d2725335ef4b.gif)

**Comment by benjamminf** [comment] 2017-03-22 21:51
I see the Neo field is localised, although that shouldn't be the problem. Do you perhaps have your "Image" field set as localisable as well? There can be unexpected behaviour when you nest localised fields.

**Comment by zachshallbetter** [comment] 2017-03-22 21:54
Yeah, they often choose different images for each language. Should it not be?
![screenshot 2017-03-22 14 54 24](https://cloud.githubusercontent.com/assets/949434/24222481/7b0f6306-0f0f-11e7-8125-59f20d3833a0.png)

**Comment by benjamminf** [comment] 2017-03-22 22:20
Ideally it shouldn't, but in my testing it typically hasn't been an issue so I haven't needed to mention it. I would bet this is the problem in this instance, though I haven't tested it. The quickest fix for this for now would be to create a second Image field that isn't localised to be used in localised Neo fields.

It'll be wise to document this somewhere, so I'll get on that ASAP

**Comment by benjamminf** [comment] 2017-04-16 09:48
I've fixed this issue with translated relational fields inside translated Neo fields. It'll be available in the next release.

**Comment by zachshallbetter** [comment] 2017-04-21 05:30
Thanks Ben

**Closed** 2017-11-10 09:34 UTC
Labels: bug, has workaround
