### ISSUE TITLE
can't save can't update

### ISSUE THREAD

**Issue by smockensturm** [benjamminf/craft-neo#14] opened 2016-05-16 15:14 UTC
- sometimes an entry with a neo field will not save. unless I add a new block, then it will save. BUT if I delete that newly added block, the entry again will not save. no warnings. nothing. (v 1.0.2 )

- upgrading from 1.0.2 to 1.1.0 screws up the database, specifically... can't find (unknown)  **neoblocks.sortOrder** column

**Comment by benjamminf** [comment] 2016-05-17 12:38
Hey @smockensturm I'm sorry using Neo hasn't been a smooth ride for you so far.

- When you say the entry will not save, what happens? Does the page reload and the entries content is just reverted? Is it only the Neo field that the content disappears from, or is it other fields in the entry as well? Can you describe what your Neo field is composed of? Namely the field types that you're using inside the blocks.
- This is a problem. I assume you've reverted back the old database by now. I've had a look into it today and didn't run into any issues. Are you getting this error during the plugin update? Or does this happen after the plugin is "successfully" updated when viewing an entry with a Neo field?

**Comment by smockensturm** [comment] 2016-05-17 12:49
Thank you. I gotta' tell you though, the pleasure of having this flexibility far outweighs the frustrations. This plug-in is a game-changer for us.

1. Yes. The page reloads and the content reverts. The neo blocks are pretty rich. We're using all kinds of stuff: asset fields, entry fields, fruiticons, lots of text fields. It's all over the place. I'm trying to remember specifically the one that was acting up, sorry. But after kicking it in the head a few times (re-arranging blocks, disabling, re-enabling...) we got back to normal. All is well at the moment.

2. The error occurs after the plug-in is "successfully" updated. Yes, we've reverted back to 1.0.2 and restored the database backup (whew) We have probably a dozen entries (singles) with a boatload of neo blocks lined up.

If you would like a temp admin access to poke around, just let me know.

Thank you.

**Comment by benjamminf** [comment] 2016-05-17 13:28
I'm happy to hear that, although ideally there'd be no frustrations ;) Seems like you're going pretty hard with it. I haven't tested Neo with too many third-party field types yet, so this could potentially be the problem. What third-party field types are you using?

1. Just to be clear, the content for the whole entry reverts? If it's the whole entry and not just the Neo field, the cause of the issue will be something completely different.

2. Okay, thanks for the clarifying. That is certainly an interesting error message, given that 1.1.0 makes no reference to the `sortOrder` column at all, except for when it drops it in the migration file. You wouldn't happen to have a copy of the SQL from after you attempting updating the plugin?

I wouldn't ask, but access to the CP would actually be ideal. It's a little late in the evening, but if you shoot me an email with the login details I can check it out as soon as I get in the office tomorrow morning.

**Comment by smockensturm** [comment] 2016-05-17 16:52
Login activation sent. (Let me know should you not receive it.)

True. It's intense. We do not have the wrecked database. We can go through the broken update again and get one if you think that would help. But hopefully, CP access will help you more. Let me know if you have questions.

(Problem #1 seems more intermittent and not as much a big deal as getting 1.1.0 up and running. That might even fix the issue. idk.)

Keep me posted. This is in pretty heavy development right now.

**Comment by benjamminf** [comment] 2016-05-18 00:32
I got the activation email and had a little poke around. Haven't found anything suspicious yet but I did notice you're hiding the checkboxes on the Neo blocks. I'd be wary about this as it won't disable the checkbox from being used, meaning you easily accidentally check a few blocks without realising. Moving or deleting a block will move or delete all the checked ones as well.

I'm on my lunch break in a few hours so I'll have better dig through.

**Comment by benjamminf** [comment] 2016-05-18 00:36
Now that I think about it, I noticed once or twice loading a page in the admin resulted in a 500 server error. Moment I refreshed it worked. It happened on pages that didn't have any reference to the Neo field so I'm doubting it had anything to do with this plugin.

**Comment by smockensturm** [comment] 2016-05-18 00:51
- So tomorrow, I'm going to go through the Neo update and get you a wrecked database to look at.

- Never, not once have we gotten a 500 server error in the CP. Ever. And a reminder of the Craft error **after** Neo update on ANY pages (CP and front end):

> can't find (unknown) neoblocks.sortOrder column

(There's more... it's in that email I sent a couple days ago.) We are running Neo 1.0.2 at the moment and it's not bad. But we don't want to be stuck there.

- We hid the checkboxes (hate that thing) for two reasons: Neo 1.0.2 has the bug that toggles it when we click a tab. And double-clicking a header to open/collapse a block toggles it on and off. Ugh. If we can successfully upgrade to 1.1.0, we'll consider un-hiding it.

Thank you again for your diligence.

**Comment by smockensturm** [comment] 2016-05-18 12:19
Well great news. Update successful! I don't know what happened. Maybe an interrupt in the database modifications. Anyway, all seems to be well. Running Neo 1.1.0 at speed. Sorry for the trouble.

**Comment by smockensturm** [comment] 2016-05-18 18:41
v 1.1.0

Still having trouble saving an entry. After adding a new block, adding the goods into it. We hit save and the page reloads and the content reverts.

**Comment by benjamminf** [comment] 2016-05-19 02:10
I'm glad you finally were able to upgrade!

I've been testing the demo page and so far I can't seem to trip it up. It does save noticeably slower, which I've determined to be caused by Neo (and I know why, and have some ideas on how to fix this).

In the meantime, I suggest enabling `devMode` in your config. That way any errors or warnings will be logged and displayed. If a non-critical error is being thrown when saving the entry, then we're probably not seeing it.

**Comment by benjamminf** [comment] 2016-09-10 06:59
Given that no one else has reported this issue, and it's age, I'm going to close this for now. If this was never solved reply back here and I'll reopen it :+1:

**Closed by benjamminf** 2016-09-10 06:59 UTC
Labels: bug, not reproducible
